// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpC_rE0S8dhOlMb44z_lUfrDuV0HLm9S8',
    appId: '1:834158685712:web:a5b57e035d82aae0746495',
    messagingSenderId: '834158685712',
    projectId: 'newfoodapp-a6edf',
    authDomain: 'newfoodapp-a6edf.firebaseapp.com',
    storageBucket: 'newfoodapp-a6edf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC91XlquS207_aCDHMh091IZpKX3C1htbY',
    appId: '1:834158685712:android:cbcceef920539248746495',
    messagingSenderId: '834158685712',
    projectId: 'newfoodapp-a6edf',
    storageBucket: 'newfoodapp-a6edf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjKgtEmqk_usZO2z9lB00u8RZKeoU9Hfs',
    appId: '1:834158685712:ios:8d7af66b1bfc716f746495',
    messagingSenderId: '834158685712',
    projectId: 'newfoodapp-a6edf',
    storageBucket: 'newfoodapp-a6edf.appspot.com',
    iosClientId: '834158685712-jvrc1hccu1nesirt9olvmj0esrk39gjb.apps.googleusercontent.com',
    iosBundleId: 'com.example.newFoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjKgtEmqk_usZO2z9lB00u8RZKeoU9Hfs',
    appId: '1:834158685712:ios:c42628b9470e1d3e746495',
    messagingSenderId: '834158685712',
    projectId: 'newfoodapp-a6edf',
    storageBucket: 'newfoodapp-a6edf.appspot.com',
    iosClientId: '834158685712-emvc0197tapqlvc0bmt6netubet02thd.apps.googleusercontent.com',
    iosBundleId: 'com.example.newFoodApp.RunnerTests',
  );
}
